# Generated by Django 4.1.3 on 2022-11-28 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('type', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('login', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservation.logincredentials')),
            ],
        ),
        migrations.CreateModel(
            name='userReservationInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('reservationTime', models.CharField(max_length=200)),
                ('reservationDate', models.CharField(max_length=200)),
                ('partySize', models.IntegerField()),
                ('restaurantName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservation.restaurant')),
                ('userName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservation.logincredentials')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twoSeats', models.IntegerField()),
                ('fourSeats', models.IntegerField()),
                ('sixSeats', models.IntegerField()),
                ('eightSeats', models.IntegerField()),
                ('restaurantName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservation.restaurant')),
            ],
        ),
    ]
